name: Infrastructure Deployment Workflow

on:
  push:
    branches:
      - main
    paths:
      - IaC/*

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: development
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
            role-to-assume: ${{ secrets.AWS_ROLE }}
            role-session-name: "GitHub_to_AWS_via_FederatedOIDC"
            aws-region: "us-east-1"

      - name: Terraform Initiate
        run: terraform -chdir=IaC/ init

      - name: Terraform Plan
        run: terraform -chdir=IaC/ plan
      
      # - name: Terraform Apply
      #   run: terraform -chdir=IaC/ apply --auto-approve

      - name: Terraform Destroy
        run: terraform destroy -auto-approve